"""rename table department to departments

Revision ID: 09e83843f3ec
Revises: c686dd31d073
Create Date: 2024-10-03 20:14:15.136387

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '09e83843f3ec'
down_revision = 'c686dd31d073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
